"""add registration_ip and plan to users

Revision ID: dcbdcf4bff3e
Revises: 3af6de8d24f6
Create Date: 2026-05-05 20:42:38.112912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcbdcf4bff3e'
down_revision: Union[str, Sequence[str], None] = '3af6de8d24f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('global_cap_state')
    op.drop_index(op.f('ix_credit_batches_user_active'), table_name='credit_batches', postgresql_where='(remaining_credits > 0)')
    op.drop_index(op.f('ix_render_jobs_dispatch'), table_name='render_jobs', postgresql_where="((deleted_at IS NULL) AND (status = ANY (ARRAY['PENDING'::render_job_status, 'PROCESSING'::render_job_status, 'FAILED'::render_job_status])))")
    op.drop_index(op.f('ix_render_jobs_locked_at'), table_name='render_jobs', postgresql_where="((status = 'PROCESSING'::render_job_status) AND (deleted_at IS NULL))")
    op.add_column('users', sa.Column('registration_ip', sa.String(length=45), nullable=True))
    
    # Thêm nullable=True trước
    op.add_column('users', sa.Column('plan', sa.String(length=50), nullable=True))
    # Set default cho rows cũ
    op.execute("UPDATE users SET plan = 'Free' WHERE plan IS NULL")
    # Đổi thành NOT NULL
    op.alter_column('users', 'plan', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    op.drop_column('users', 'registration_ip')
    op.create_index(op.f('ix_render_jobs_locked_at'), 'render_jobs', ['locked_at'], unique=False, postgresql_where="((status = 'PROCESSING'::render_job_status) AND (deleted_at IS NULL))")
    op.create_index(op.f('ix_render_jobs_dispatch'), 'render_jobs', ['status', sa.literal_column('priority DESC'), 'created_at'], unique=False, postgresql_where="((deleted_at IS NULL) AND (status = ANY (ARRAY['PENDING'::render_job_status, 'PROCESSING'::render_job_status, 'FAILED'::render_job_status])))")
    op.create_index(op.f('ix_credit_batches_user_active'), 'credit_batches', ['user_id', 'expires_at', 'created_at'], unique=False, postgresql_where='(remaining_credits > 0)')
    op.create_table('global_cap_state',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('date_bucket', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('current_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_per_day', sa.INTEGER(), server_default=sa.text('1000'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('chk_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('global_cap_state_pkey'))
    )
    # ### end Alembic commands ###
