"""fix plan default to FREE uppercase

Revision ID: f687e35c8ae9
Revises: dcbdcf4bff3e
Create Date: 2026-05-05 21:54:12.313942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f687e35c8ae9'
down_revision: Union[str, Sequence[str], None] = 'dcbdcf4bff3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
